[package]
name = "codecophony_editor_frontend"
version = "0.1.0"
authors = ["Eli Dupree <vcs@elidupree.com>"]

[dependencies]
codecophony_editor_shared = {path="../codecophony_editor_shared"}
stdweb = "0.4"
serde_json = "1.0"
serde = "1.0"
rand = "0.6"
nalgebra = "0.16"
