[package]
name = "codecophony"
version = "0.1.0"
authors = ["Eli Dupree <vcs@elidupree.com>"]

[dependencies.fluidsynth]
git = "https://github.com/elidupree/rust-fluidsynth"

[dependencies]
cpal = "0.2.8"
hound = "1.1.0"